/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package iss_project5;

import java.io.*;
import java.sql.*;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Bcc
 */
public class AddRequest extends javax.swing.JFrame {
    Request request= new Request();
    Password password= new Password();
    User user = new User();
    static ArrayList list;
    /**
     * Creates new form AddRequest
     */
    public AddRequest() {
        initComponents();
        setTable(list);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        user_id = new javax.swing.JTextField();
        title = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        sharedPassword = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel2.setText("User Identity");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel3.setText("Password Title");

        user_id.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N

        title.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        title.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                titleActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 255, 153));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        sharedPassword.setAutoCreateRowSorter(true);
        sharedPassword.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sharedPassword.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "User Id", "Title", "Password", "Description"
            }
        ));
        jScrollPane1.setViewportView(sharedPassword);
        if (sharedPassword.getColumnModel().getColumnCount() > 0) {
            sharedPassword.getColumnModel().getColumn(0).setMinWidth(80);
            sharedPassword.getColumnModel().getColumn(0).setMaxWidth(100);
            sharedPassword.getColumnModel().getColumn(1).setMinWidth(100);
            sharedPassword.getColumnModel().getColumn(1).setMaxWidth(120);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(user_id, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(title))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(user_id, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(56, 56, 56)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void titleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_titleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_titleActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        password.user_id = Client.user.userId;
        password.title=title.getText();
        user.userId = Integer.parseInt(user_id.getText());
        try {
            request.type = 7;
            request.password = this.password;
            request.user = this.user;
            Client.send_request(request);
        } catch (IOException ex) {
           System.out.println(ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AddPassword.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(AddPassword.class.getName()).log(Level.SEVERE, null, ex);
        }
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(ArrayList list) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddRequest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddRequest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddRequest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddRequest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
//        AddRequest obj = new AddRequest();
//        obj.setTable(list);
        AddRequest.list = list;
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddRequest().setVisible(true);
            }
        });
    }
    
    public void setTable(ArrayList requests)
    {
        DefaultTableModel table= (DefaultTableModel)sharedPassword.getModel();
        Object[] data = new Object[5];
        if(requests!=null)
        {
            for(int i=0 ;i<requests.size();i++)
            {
                SharePassword sp = (SharePassword) requests.get(i);
                try {
                    sp.RSA_Decode(Client.user.privateKey);
                } catch (Exception ex) {
                    Logger.getLogger(ShowRequest.class.getName()).log(Level.SEVERE, null, ex);
                }
                data[0] = sp.user_id1;
                data[1] = sp.password.title;
                data[2] = sp.password.password;
                data[3] = sp.password.description;
                System.out.println("data: "+data);
                table.addRow(data);
            }
        }
    }
    
    public static ArrayList myRequests(Request request)
    {
        System.out.println("myrequests");
        ArrayList list = new ArrayList();
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/iss_project", "root", "");
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery("SELECT * FROM requests");
            while(rs.next())
            {
                if(request.user.userId== rs.getInt(3) && rs.getInt(8)==1)
                {
                    SharePassword sp = new SharePassword();
                    sp.id = rs.getInt(1);
                    sp.user_id1 = rs.getInt(2);
                    sp.user_id2 = rs.getInt(3);
                    sp.password.title = rs.getString(4); 
                    sp.password.password = rs.getString(5); 
                    sp.password.description = rs.getString(6); 
                    Blob blob = rs.getBlob(7);
                    if(blob!=null)
                    {
                        int blobLength = (int) blob.length();
                        sp.password.file = blob.getBytes(1, blobLength);
                        blob.free();
                    } 
                    list.add(sp);
                }
            }
            con.close();
        } catch (Exception ex) {
            Logger.getLogger(AddRequest.class.getName()).log(Level.SEVERE, null, ex);
        }
        System.out.println("list in Add Request: "+list);
        return list;
    }
    
    public static Response process(Request request)
    {
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/iss_project", "root", "");
            Statement stmt = con.createStatement();
            PreparedStatement pstmt = con.prepareStatement("INSERT INTO requests (id,user_id1,user_id2,password_title,password,description,file,accepted) VALUES (?, ?, ?, ?, ?, ?, ?, ?)");  
            pstmt.setInt(1, 0);
            pstmt.setInt(2, request.password.user_id);
            pstmt.setInt(3, request.user.userId);
            pstmt.setString(4, request.password.title);
            pstmt.setString(5, request.password.password);
            pstmt.setString(6, request.password.description);
            if(request.password.file !=null)
            {
                ByteArrayInputStream bais = new ByteArrayInputStream(request.password.file);
                pstmt.setBlob(7, bais); 
            }
            else
            {
                ByteArrayInputStream bais=null;
                pstmt.setBlob(7, bais); 
            }
            pstmt.setInt(8, 0);
            pstmt.executeUpdate(); 
            con.close();
        }catch(Exception e){
            System.out.println(e);
        }
        Response response = new Response();
        response.msg = "success";
        return response;
    }
    
    public static void next_step()
    {
        UserRequest.main();
    }
    
    public static void same_step()
    {
        AddRequest.main(AddRequest.list);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable sharedPassword;
    private javax.swing.JTextField title;
    private javax.swing.JTextField user_id;
    // End of variables declaration//GEN-END:variables
}
